///@description KSW - UI - Customize - Set Pages

function scr_KSW_UI_Customize_SetPages()
{
	#region Setup
	KSW_PageCount = 0;
	
	KSW_PageList = [];
	KSW_PageIDs = ds_map_create();
	#endregion
	
	#region Add Pages Here
	scr_KSW_UI_Customize_AddPage("main",scr_KSW_UI_Customize_Pages_Main_Setup,scr_KSW_UI_Customize_Pages_Main_Main,scr_KSW_UI_Customize_Pages_Main_Select,scr_KSW_UI_Customize_Pages_Main_Back,scr_KSW_UI_Customize_Pages_Main_Up,scr_KSW_UI_Customize_Pages_Main_Down,scr_KSW_UI_Customize_Pages_Main_Left,scr_KSW_UI_Customize_Pages_Main_Right,scr_KSW_UI_Customize_Pages_Main_L,scr_KSW_UI_Customize_Pages_Main_R,scr_KSW_UI_Customize_Pages_Main_Draw);
	scr_KSW_UI_Customize_AddPage("characters",scr_KSW_UI_Customize_Pages_Characters_Setup,scr_KSW_UI_Customize_Pages_Characters_Main,scr_KSW_UI_Customize_Pages_Characters_Select,scr_KSW_UI_Customize_Pages_Characters_Back,scr_KSW_UI_Customize_Pages_Characters_Up,scr_KSW_UI_Customize_Pages_Characters_Down,scr_KSW_UI_Customize_Pages_Characters_Left,scr_KSW_UI_Customize_Pages_Characters_Right,scr_KSW_UI_Customize_Pages_Characters_L,scr_KSW_UI_Customize_Pages_Characters_R,scr_KSW_UI_Customize_Pages_Characters_Draw);
	scr_KSW_UI_Customize_AddPage("sprayPaints",scr_KSW_UI_Customize_Pages_SprayPaints_Setup,scr_KSW_UI_Customize_Pages_SprayPaints_Main,scr_KSW_UI_Customize_Pages_SprayPaints_Select,scr_KSW_UI_Customize_Pages_SprayPaints_Back,scr_KSW_UI_Customize_Pages_SprayPaints_Up,scr_KSW_UI_Customize_Pages_SprayPaints_Down,scr_KSW_UI_Customize_Pages_SprayPaints_Left,scr_KSW_UI_Customize_Pages_SprayPaints_Right,scr_KSW_UI_Customize_Pages_SprayPaints_L,scr_KSW_UI_Customize_Pages_SprayPaints_R,scr_KSW_UI_Customize_Pages_SprayPaints_Draw);
	scr_KSW_UI_Customize_AddPage("hats",scr_KSW_UI_Customize_Pages_Hats_Setup,scr_KSW_UI_Customize_Pages_Hats_Main,scr_KSW_UI_Customize_Pages_Hats_Select,scr_KSW_UI_Customize_Pages_Hats_Back,scr_KSW_UI_Customize_Pages_Hats_Up,scr_KSW_UI_Customize_Pages_Hats_Down,scr_KSW_UI_Customize_Pages_Hats_Left,scr_KSW_UI_Customize_Pages_Hats_Right,scr_KSW_UI_Customize_Pages_Hats_L,scr_KSW_UI_Customize_Pages_Hats_R,scr_KSW_UI_Customize_Pages_Hats_Draw);
	scr_KSW_UI_Customize_AddPage("bobbers",scr_KSW_UI_Customize_Pages_Bobbers_Setup,scr_KSW_UI_Customize_Pages_Bobbers_Main,scr_KSW_UI_Customize_Pages_Bobbers_Select,scr_KSW_UI_Customize_Pages_Bobbers_Back,scr_KSW_UI_Customize_Pages_Bobbers_Up,scr_KSW_UI_Customize_Pages_Bobbers_Down,scr_KSW_UI_Customize_Pages_Bobbers_Left,scr_KSW_UI_Customize_Pages_Bobbers_Right,scr_KSW_UI_Customize_Pages_Bobbers_L,scr_KSW_UI_Customize_Pages_Bobbers_R,scr_KSW_UI_Customize_Pages_Bobbers_Draw);
	scr_KSW_UI_Customize_AddPage("baits",scr_KSW_UI_Customize_Pages_Baits_Setup,scr_KSW_UI_Customize_Pages_Baits_Main,scr_KSW_UI_Customize_Pages_Baits_Select,scr_KSW_UI_Customize_Pages_Baits_Back,scr_KSW_UI_Customize_Pages_Baits_Up,scr_KSW_UI_Customize_Pages_Baits_Down,scr_KSW_UI_Customize_Pages_Baits_Left,scr_KSW_UI_Customize_Pages_Baits_Right,scr_KSW_UI_Customize_Pages_Baits_L,scr_KSW_UI_Customize_Pages_Baits_R,scr_KSW_UI_Customize_Pages_Baits_Draw);
	scr_KSW_UI_Customize_AddPage("music",scr_KSW_UI_Customize_Pages_Music_Setup,scr_KSW_UI_Customize_Pages_Music_Main,scr_KSW_UI_Customize_Pages_Music_Select,scr_KSW_UI_Customize_Pages_Music_Back,scr_KSW_UI_Customize_Pages_Music_Up,scr_KSW_UI_Customize_Pages_Music_Down,scr_KSW_UI_Customize_Pages_Music_Left,scr_KSW_UI_Customize_Pages_Music_Right,scr_KSW_UI_Customize_Pages_Music_L,scr_KSW_UI_Customize_Pages_Music_R,scr_KSW_UI_Customize_Pages_Music_Draw);
	scr_KSW_UI_Customize_AddPage("stages",scr_KSW_UI_Customize_Pages_Stages_Setup,scr_KSW_UI_Customize_Pages_Stages_Main,scr_KSW_UI_Customize_Pages_Stages_Select,scr_KSW_UI_Customize_Pages_Stages_Back,scr_KSW_UI_Customize_Pages_Stages_Up,scr_KSW_UI_Customize_Pages_Stages_Down,scr_KSW_UI_Customize_Pages_Stages_Left,scr_KSW_UI_Customize_Pages_Stages_Right,scr_KSW_UI_Customize_Pages_Stages_L,scr_KSW_UI_Customize_Pages_Stages_R,scr_KSW_UI_Customize_Pages_Stages_Draw);
	#endregion
}