///@description KSW - Set Flavor Text

function scr_KSW_SetFlavorText()
{
	flavorTextArray =
	[
	"Soda Fishing!",
	"From Strimp's Kitchen!",
	"Catch Catch Catch!",
	"Added Soft, Working on Wet!",
	"You’ll Float Too!",
	"Get Jerryfish!",
	"This Writing Is Soggy!",
	"Bass Fishing of the Dead!",
	"That’s the Wonder of Fishing!",
	"Fish Frenzy!",
	"You Know What That Means!",
	"Bubble Bass!",
	"Got Wet, But Getting Soft!",
	"Where's the Fanfic, Text Overflowed?",
	"MUST FISH MUST FISH!",
	"German Fish!",
	"Are Catfish Fish or Cats?",
	"How’s The Signal Underwater?",
	"Please Do Not Announce to the Server When You’re Going to Fish!",
	"I Would Use the Car, BUT THE GOLDFISH TOOK IT!",
	"Still No Copy Abilities!",
	"Buriki!",
	"Every Fish You Collect Can Be Turned Into a Fish Fillet!",
	"Hey Bass! Why Must I Fight You!? We Are Not Enemies!",
	"Kirby Gamble Galaxy Fishing!",
	"Eternity!",
	"Klaus!",
	"MY LEG!",
	"Help Bloppo, He Can’t Swim!",
	"Rain or Shine, All Fish Are Mine!",
	"When's Stardream Fishwork!",
	"This Alien Medal Is Useless, Ika!",
	"Kirby of the Seas",
	"Kirby of the Saltwater",
	"That One Didn’t Flow Quite So Well!",
	"Hello. I am Under the Water, Please Help!",
	"'ÆUGH' - That one Pufferfish",
	"Berries!",
	"The Title doesn’t lie!",
	"The Title Don’t Lie, It’s Anything but Dry!",
	"When's Kirby Hard and Dry?",
	"Pufferfish = Needle Kirby!",
	"Better Fishing Minigame Than Forgotten Land???",
	"Small One/Medium/Big One/Huge!",
	"The Game That Smiles Back!",
	"Sweeter Stuff!",
	"Magolor Was Here!",
	"I Was Hit By a Truck and Reborn As a Pink Blob With a Yearning to Fish!?!",
	"Why is Lovely an Aquatic Enemy?",
	"Dedede-Man Drowns!",
	"It’s incredible! WATER KIRBYSAURUS!",
	"As A Puffball, I Yearn For The Fish!",
	"Just Like the Intro in DL3!",
	"I Want an Ice Cream Sandwich!",
	"You’re Telling Me a Strimp Softened This Wet Fish?",
	"I AM THE GAME THAT THEY CALL SOFT & WET!",
	"LALALALALA SOFT AND WEEET!!",
	"Find the Fecal Fish...",
	"Who Up Softing Their Wet RN?",
	"More Fish for the Kitchen...",
	"You Know What That Means, FISH!",
	"Fish Lips, Fish Lips, Gimme Lots Of Fish Lips!",
	"Sweet Mother of Almonds!",
	"Kirby's Return To Fishland!",
	"How Do You Fish With Those Stubby Hands?",
	"0% Storytelling, 0% New Mechanics, 100% Fishing Minigames!",
	"Never Gonna Fish You Up!",
	"https://www.youtube.com/watch?v=dQw4w9WgXcQ",
	"I’m-a Guess I’m-a Go Feeshing!",
	"Kirby, Go Fish!",
	"Looks Like it’s Time to Go Feeshing Again!",
	"One Game! Over 100 Different Names for It!",
	"He’s Softer, Wetter, and Fishy, Too!",
	"I Like Moisture In My Food!",
	"A Communication Error Occurred!",
	"Have a Fish, Mr. Kirby!",
	"Squishy & Moist!",
	"Yes, We Know It’s O-Fish-Al!",
	"Fishi no Kābī!",
	"Want to Catch Some Fish?",
	"I Support Fish!",
	"Can You Catch the Big Guy?",
	"Great! I’m-a fish!",
	"Coffee’sh?",
	"Moist!",
	"Can You Beat This Game With No Z Presses?",
	"New Funky Mode!",
	"Catch Catch Catch!"
	];
	
	var flavorText = flavorTextArray[irandom_range(0,array_length(flavorTextArray) - 1)];
	flavorTextArray = -1;
	
	return flavorText;
}