///@description KSW - Set Fishes

function scr_KSW_SetFishes()
{
	#region Setup
	global.KSW_FishCount = 0;
	
	global.KSW_FishList = [];
	global.KSW_FishIDs = ds_map_create();
	#endregion
	
	#region Caught Box Palettes
	var candy = spr_KSW_UI_CaughtBox_Palette_Candy;
	var mint = spr_KSW_UI_CaughtBox_Palette_Mint;
	var legion = spr_KSW_UI_CaughtBox_Palette_Legion;
	var mage = spr_KSW_UI_CaughtBox_Palette_Mage;
	var glimmer = spr_KSW_UI_CaughtBox_Palette_Glimmer;
	var borange = spr_KSW_UI_CaughtBox_Palette_Borange;
	var flux = spr_KSW_UI_CaughtBox_Palette_Flux;
	var tvtime = spr_KSW_UI_CaughtBox_Palette_TVTime;
	#endregion
	
	#region Add Fishes Here
	scr_KSW_AddFish("Blipper",spr_KSW_Fish_Blipper,spr_KSW_Fish_Blipper_Pal_Normal,candy,0,KSW_Phases.day,500);
	scr_KSW_AddFish("Slippy",spr_KSW_Fish_Slippy,spr_KSW_Fish_Slippy_Pal_Normal,borange,0,KSW_Phases.day,400);
	scr_KSW_AddFish("Glunk",spr_KSW_Fish_Glunk,spr_KSW_Fish_Glunk_Pal_Normal,mint,0,KSW_Phases.day,450);
	scr_KSW_AddFish("Diving Gordo",spr_KSW_Fish_DivingGordo,spr_KSW_Fish_DivingGordo_Pal_Normal,flux,1,KSW_Phases.day,800);
	scr_KSW_AddFish("Leap",spr_KSW_Fish_Leap,spr_KSW_Fish_Leap_Pal_Normal,mage,0,KSW_Phases.day,300);
	scr_KSW_AddFish("Gusso",spr_KSW_Fish_Gusso,spr_KSW_Fish_Gusso_Pal_Normal,mage,0,KSW_Phases.afternoon,600,-3,0);
	scr_KSW_AddFish("Joe",spr_KSW_Fish_Joe,spr_KSW_Fish_Joe_Pal_Normal,mage,0,KSW_Phases.night,2000,-2,1);
	scr_KSW_AddFish("Pacto",spr_KSW_Fish_Pacto,spr_KSW_Fish_Pacto_Pal_Normal,glimmer,1,KSW_Phases.night,2500,0,-2);
	scr_KSW_AddFish("Squishy",spr_KSW_Fish_Squishy,spr_KSW_Fish_Squishy_Pal_Normal,mage,0,KSW_Phases.afternoon,1000);
	scr_KSW_AddFish("Flotzo",spr_KSW_Fish_Flotzo,spr_KSW_Fish_Flotzo_Pal_Normal,candy,0,KSW_Phases.afternoon,1500);
	scr_KSW_AddFish("Peezer",spr_KSW_Fish_Peezer,spr_KSW_Fish_Peezer_Pal_Normal,mage,0,KSW_Phases.afternoon,400,0,1);
	scr_KSW_AddFish("Tortletummy",spr_KSW_Fish_Tortletummy,spr_KSW_Fish_Tortletummy_Pal_Normal,mint,2,KSW_Phases.afternoon,15000,10,30);
	scr_KSW_AddFish("Stickle",spr_KSW_Fish_Stickle,spr_KSW_Fish_Stickle_Pal_Normal,legion,0,KSW_Phases.afternoon,750);
	scr_KSW_AddFish("Squister",spr_KSW_Fish_Squister,spr_KSW_Fish_Squister_Pal_Normal,mage,0,KSW_Phases.afternoon,1000);
	scr_KSW_AddFish("Slugoo",spr_KSW_Fish_Slugoo,spr_KSW_Fish_Slugoo_Pal_Normal,mint,0,KSW_Phases.day,3000);
	scr_KSW_AddFish("Elebli",spr_KSW_Fish_Elebli,spr_KSW_Fish_Elebli_Pal_Normal,glimmer,0,KSW_Phases.night,500,-3,0);
	scr_KSW_AddFish("Blish",spr_KSW_Fish_Blish,spr_KSW_Fish_Blish_Pal_Normal,mint,0,KSW_Phases.day,15000,-16);
	scr_KSW_AddFish("King Eelongo",spr_KSW_Fish_KingEelongo,spr_KSW_Fish_KingEelongo_Pal_Normal,borange,3,KSW_Phases.night,60000,-175,24);
	scr_KSW_AddFish("Acro",spr_KSW_Fish_Acro,spr_KSW_Fish_Acro_Pal_Normal,legion,2,KSW_Phases.night,30000,-19,0);
	scr_KSW_AddFish("Fatty Whale",spr_KSW_Fish_FattyWhale,spr_KSW_Fish_FattyWhale_Pal_Normal,mage,3,KSW_Phases.afternoon,50000,-32,10);
	scr_KSW_AddFish("Mini Gobbler",spr_KSW_Fish_MiniGobbler,spr_KSW_Fish_MiniGobbler_Pal_Normal,candy,0,KSW_Phases.night,800);
	scr_KSW_AddFish("Gobbler",spr_KSW_Fish_Gobbler,spr_KSW_Fish_Gobbler_Pal_Normal,mage,2,KSW_Phases.night,20000,-12,2);
	scr_KSW_AddFish("Kine",spr_KSW_Fish_Kine,spr_KSW_Fish_Kine_Pal_Normal,mage,1,KSW_Phases.day,7500,-4);
	scr_KSW_AddFish("Merman",spr_KSW_Fish_Merman,spr_KSW_Fish_Merman_Pal_Normal,borange,1,KSW_Phases.night,2000,2,12);
	scr_KSW_AddFish("Giant Merman",spr_KSW_Fish_GiantMerman,spr_KSW_Fish_GiantMerman_Pal_Normal,mint,2,KSW_Phases.night,10000,-10,14);
	scr_KSW_AddFish("Fish Head",spr_KSW_Fish_FishHead,spr_KSW_Fish_FishHead_Pal_Normal,legion,1,KSW_Phases.night,3000,-10,14);
	scr_KSW_AddFish("Peeping Eye",spr_KSW_Fish_PeepingEye,spr_KSW_Fish_PeepingEye_Pal_Normal,borange,2,KSW_Phases.afternoon,6000,0,16);
	scr_KSW_AddFish("Peeping Big",spr_KSW_Fish_PeepingBig,spr_KSW_Fish_PeepingBig_Pal_Normal,borange,3,KSW_Phases.afternoon,14000,-1,18);
	scr_KSW_AddFish("Metroid",spr_KSW_Fish_Metroid,spr_KSW_Fish_Metroid_Pal_Normal,mint,1,KSW_Phases.afternoon,2500);
	scr_KSW_AddFish("Skultera",spr_KSW_Fish_Skultera,spr_KSW_Fish_Skultera_Pal_Normal,flux,0,KSW_Phases.night,1000,-8,-4);
	scr_KSW_AddFish("Evir",spr_KSW_Fish_Evir,spr_KSW_Fish_Evir_Pal_Normal,borange,0,KSW_Phases.afternoon,900,-4,8);
	scr_KSW_AddFish("Draygon",spr_KSW_Fish_Draygon,spr_KSW_Fish_Draygon_Pal_Normal,mint,2,KSW_Phases.afternoon,30000,-30,36);
	scr_KSW_AddFish("Phantoon",spr_KSW_Fish_Phantoon,spr_KSW_Fish_Phantoon_Pal_Normal,mint,2,KSW_Phases.night,20000,0,-16);
	scr_KSW_AddFish("Botwoon",spr_KSW_Fish_Botwoon,spr_KSW_Fish_Botwoon_Pal_Normal,borange,1,KSW_Phases.night,10000,-44,30);
	scr_KSW_AddFish("Serris",spr_KSW_Fish_Serris,spr_KSW_Fish_Serris_Pal_Normal,mint,2,KSW_Phases.afternoon,40000,-86,-8);
	scr_KSW_AddFish("Guppy",spr_KSW_Fish_Guppy,spr_KSW_Fish_Guppy_Pal_Normal,candy,0,KSW_Phases.day,500);
	scr_KSW_AddFish("Carnivore",spr_KSW_Fish_Carnivore,spr_KSW_Fish_Carnivore_Pal_Normal,legion,0,KSW_Phases.day,750,-1,3);
	scr_KSW_AddFish("Starcatcher",spr_KSW_Fish_Starcatcher,spr_KSW_Fish_Starcatcher_Pal_Normal,glimmer,0,KSW_Phases.afternoon,750);
	scr_KSW_AddFish("Fecal Forgo",spr_KSW_Fish_FecalForgo,spr_KSW_Fish_FecalForgo_Pal_Normal,mint,3,KSW_Phases.day,100000);
	scr_KSW_AddFish("Red Cheep Cheep",spr_KSW_Fish_CheepCheepRed,spr_KSW_Fish_CheepCheepRed_Pal_Normal,candy,0,KSW_Phases.afternoon,400);
	scr_KSW_AddFish("Green Cheep Cheep",spr_KSW_Fish_CheepCheepGreen,spr_KSW_Fish_CheepCheepGreen_Pal_Normal,mint,0,KSW_Phases.day,400);
	scr_KSW_AddFish("Blooper",spr_KSW_Fish_Blooper,spr_KSW_Fish_Blooper_Pal_Normal,glimmer,0,KSW_Phases.day,1000);
	scr_KSW_AddFish("Bloopad",spr_KSW_Fish_Bloopad,spr_KSW_Fish_Bloopad_Pal_Normal,glimmer,0,KSW_Phases.day,1000);
	scr_KSW_AddFish("Blurp",spr_KSW_Fish_Blurp,spr_KSW_Fish_Blurp_Pal_Normal,mint,0,KSW_Phases.day,600);
	scr_KSW_AddFish("Rip Van Fish",spr_KSW_Fish_RipVanFish,spr_KSW_Fish_RipVanFish_Pal_Normal,flux,0,KSW_Phases.day,800);
	scr_KSW_AddFish("Fish Bone",spr_KSW_Fish_FishBone,spr_KSW_Fish_FishBone_Pal_Normal,legion,1,KSW_Phases.night,1200,-2,0);
	scr_KSW_AddFish("Morton",spr_KSW_Fish_Morton,spr_KSW_Fish_Morton_Pal_Normal,mage,3,KSW_Phases.afternoon,30000,-2,2);
	scr_KSW_AddFish("Sonic the Fish",spr_KSW_Fish_SonicFish,spr_KSW_Fish_SonicFish_Pal_Normal,legion,3,KSW_Phases.day,30000,-38,-16);
	scr_KSW_AddFish("Ring",spr_KSW_Fish_Ring,spr_KSW_Fish_Ring_Pal_Normal,glimmer,1,KSW_Phases.day,2500,-8,-8);
	scr_KSW_AddFish("Star Post",spr_KSW_Fish_StarPost,spr_KSW_Fish_StarPost_Pal_Normal,legion,2,KSW_Phases.afternoon,4250,-8,-16);
	scr_KSW_AddFish("Goal Plate",spr_KSW_Fish_GoalPlate,spr_KSW_Fish_GoalPlate_Pal_Normal,candy,2,KSW_Phases.afternoon,8500,-20,-16);
	scr_KSW_AddFish("Item Box",spr_KSW_Fish_ItemBox,spr_KSW_Fish_ItemBox_Pal_Normal,mage,1,KSW_Phases.night,4000,-15,-12);
	scr_KSW_AddFish("Spring",spr_KSW_Fish_Spring,spr_KSW_Fish_Spring_Pal_Normal,candy,0,KSW_Phases.night,500,-16,-20);
	scr_KSW_AddFish("Chopper",spr_KSW_Fish_Chopper,spr_KSW_Fish_Chopper_Pal_Normal,candy,0,KSW_Phases.day,2000,-8,-1);
	scr_KSW_AddFish("Crabmeat",spr_KSW_Fish_Crabmeat,spr_KSW_Fish_Crabmeat_Pal_Normal,candy,0,KSW_Phases.day,3000,0,4);
	scr_KSW_AddFish("Masher",spr_KSW_Fish_Masher,spr_KSW_Fish_Masher_Pal_Normal,candy,0,KSW_Phases.day,1500,-6,2);
	scr_KSW_AddFish("Chop Chop",spr_KSW_Fish_ChopChop,spr_KSW_Fish_ChopChop_Pal_Normal,legion,0,KSW_Phases.afternoon,1000,-4,0);
	scr_KSW_AddFish("Aquis",spr_KSW_Fish_Aquis,spr_KSW_Fish_Aquis_Pal_Normal,mint,1,KSW_Phases.afternoon,2500,-2,12);
	scr_KSW_AddFish("Shellcracker",spr_KSW_Fish_Shellcracker,spr_KSW_Fish_Shellcracker_Pal_Normal,candy,1,KSW_Phases.afternoon,5000);
	scr_KSW_AddFish("Asteron",spr_KSW_Fish_Asteron,spr_KSW_Fish_Asteron_Pal_Normal,borange,0,KSW_Phases.afternoon,2000);
	scr_KSW_AddFish("Turtloid",spr_KSW_Fish_Turtloid,spr_KSW_Fish_Turtloid_Pal_Normal,mint,2,KSW_Phases.afternoon,8000,-24,-12);
	scr_KSW_AddFish("Pointdexter",spr_KSW_Fish_Pointdexter,spr_KSW_Fish_Pointdexter_Pal_Normal,legion,1,KSW_Phases.night,4000,-6,2);
	scr_KSW_AddFish("Turbo Spiker",spr_KSW_Fish_TurboSpiker,spr_KSW_Fish_TurboSpiker_Pal_Normal,candy,1,KSW_Phases.afternoon,4500,-8,-2);
	scr_KSW_AddFish("Mega Chopper",spr_KSW_Fish_MegaChopper,spr_KSW_Fish_MegaChopper_Pal_Normal,candy,0,KSW_Phases.day,800,-2,0);
	scr_KSW_AddFish("Jawz",spr_KSW_Fish_Jawz,spr_KSW_Fish_Jawz_Pal_Normal,mage,1,KSW_Phases.night,2500,-18,0);
	scr_KSW_AddFish("Doshin",spr_KSW_Fish_Doshin,spr_KSW_Fish_Doshin_Pal_Normal,borange,3,KSW_Phases.day,90000,9,218);
	scr_KSW_AddFish("Bloppo The Warbler",spr_KSW_Fish_Bloppo,spr_KSW_Fish_Bloppo_Pal_Normal,candy,3,KSW_Phases.afternoon,60000,2,60);
	scr_KSW_AddFish("Octorok",spr_KSW_Fish_Octorok,spr_KSW_Fish_Octorok_Pal_Normal,candy,0,KSW_Phases.afternoon,3000,1,0);
	scr_KSW_AddFish("Big Octorok",spr_KSW_Fish_BigOctorok,spr_KSW_Fish_BigOctorok_Pal_Normal,candy,1,KSW_Phases.afternoon,12000,-30,0);
	scr_KSW_AddFish("Chuchu",spr_KSW_Fish_Chuchu,spr_KSW_Fish_Chuchu_Pal_Normal,legion,0,KSW_Phases.day,2500);
	scr_KSW_AddFish("Big Chuchu",spr_KSW_Fish_BigChuchu,spr_KSW_Fish_BigChuchu_Pal_Normal,legion,1,KSW_Phases.day,14000,0,14);
	scr_KSW_AddFish("Sluggula",spr_KSW_Fish_Sluggula,spr_KSW_Fish_Sluggula_Pal_Normal,legion,0,KSW_Phases.day,1500);
	scr_KSW_AddFish("Cloud Piranha",spr_KSW_Fish_CloudPiranha,spr_KSW_Fish_CloudPiranha_Pal_Normal,legion,0,KSW_Phases.afternoon,1000,-1,-2);
	scr_KSW_AddFish("Zora",spr_KSW_Fish_Zora,spr_KSW_Fish_Zora_Pal_Normal,mint,1,KSW_Phases.night,5000,0,-1);
	scr_KSW_AddFish("Ganondorf",spr_KSW_Fish_Ganondorf,spr_KSW_Fish_Ganondorf_Pal_Normal,mage,3,KSW_Phases.night,60000,-6,36);
	scr_KSW_AddFish("Atlantic Cod",spr_KSW_Fish_AtlanticCod,spr_KSW_Fish_AtlanticCod_Pal_Normal,candy,0,KSW_Phases.none,870);
	scr_KSW_AddFish("Neon Tetra",spr_KSW_Fish_NeonTetra,spr_KSW_Fish_NeonTetra_Pal_Normal,legion,0,KSW_Phases.none,90);
	scr_KSW_AddFish("Red Snapper",spr_KSW_Fish_RedSnapper,spr_KSW_Fish_RedSnapper_Pal_Normal,candy,0,KSW_Phases.none,820);
	scr_KSW_AddFish("Tuna",spr_KSW_Fish_Tuna,spr_KSW_Fish_Tuna_Pal_Normal,mage,0,KSW_Phases.none,980);
	scr_KSW_AddFish("Salmon",spr_KSW_Fish_Salmon,spr_KSW_Fish_Salmon_Pal_Normal,glimmer,0,KSW_Phases.none,1100);
	scr_KSW_AddFish("Bass",spr_KSW_Fish_Bass,spr_KSW_Fish_Bass_Pal_Normal,mage,0,KSW_Phases.none,740);
	scr_KSW_AddFish("Flounder",spr_KSW_Fish_Flounder,spr_KSW_Fish_Flounder_Pal_Normal,mage,0,KSW_Phases.none,690);
	scr_KSW_AddFish("Rock Lobster",spr_KSW_Fish_RockLobster,spr_KSW_Fish_RockLobster_Pal_Normal,candy,0,KSW_Phases.none,920);
	scr_KSW_AddFish("Trout",spr_KSW_Fish_Trout,spr_KSW_Fish_Trout_Pal_Normal,mage,0,KSW_Phases.none,800);
	scr_KSW_AddFish("Shrimp",spr_KSW_Fish_Shrimp,spr_KSW_Fish_Shrimp_Pal_Normal,legion,0,KSW_Phases.none,60);
	scr_KSW_AddFish("Crimson Tigerfish",spr_KSW_Fish_CrimsonTigerfish,spr_KSW_Fish_CrimsonTigerfish_Pal_Normal,candy,1,KSW_Phases.none,970);
	scr_KSW_AddFish("Specular Fish",spr_KSW_Fish_SpecularFish,spr_KSW_Fish_SpecularFish_Pal_Normal,legion,1,KSW_Phases.none,1300);
	scr_KSW_AddFish("Blue Jellyfish (Bait)",spr_KSW_Fish_BlueJellyfishBait,spr_KSW_Fish_BlueJellyfishBait_Pal_Normal,legion,1,KSW_Phases.none,230);
	scr_KSW_AddFish("Green Jellyfish (Bait)",spr_KSW_Fish_GreenJellyfishBait,spr_KSW_Fish_GreenJellyfishBait_Pal_Normal,mint,1,KSW_Phases.none,250);
	scr_KSW_AddFish("Pink Jellyfish (Bait)",spr_KSW_Fish_PinkJellyfishBait,spr_KSW_Fish_PinkJellyfishBait_Pal_Normal,glimmer,1,KSW_Phases.none,270);
	scr_KSW_AddFish("Stinkfish",spr_KSW_Fish_Stinkfish,spr_KSW_Fish_Stinkfish_Pal_Normal,mint,1,KSW_Phases.none,470);
	scr_KSW_AddFish("Armored Cavefish",spr_KSW_Fish_ArmoredCavefish,spr_KSW_Fish_ArmoredCavefish_Pal_Normal,flux,1,KSW_Phases.none,3400);
	scr_KSW_AddFish("Damselfish",spr_KSW_Fish_Damselfish,spr_KSW_Fish_Damselfish_Pal_Normal,mage,1,KSW_Phases.none,880);
	scr_KSW_AddFish("Double Cod",spr_KSW_Fish_DoubleCod,spr_KSW_Fish_DoubleCod_Pal_Normal,mint,1,KSW_Phases.none,1600);
	scr_KSW_AddFish("Ebonkoi",spr_KSW_Fish_Ebonkoi,spr_KSW_Fish_Ebonkoi_Pal_Normal,flux,1,KSW_Phases.none,1700);
	scr_KSW_AddFish("Frost Minnow",spr_KSW_Fish_FrostMinnow,spr_KSW_Fish_FrostMinnow_Pal_Normal,legion,1,KSW_Phases.none,360);
	scr_KSW_AddFish("Hemopiranha",spr_KSW_Fish_Hemopiranha,spr_KSW_Fish_Hemopiranha_Pal_Normal,candy,1,KSW_Phases.none,520);
	scr_KSW_AddFish("Honeyfin",spr_KSW_Fish_Honeyfin,spr_KSW_Fish_Honeyfin_Pal_Normal,borange,1,KSW_Phases.none,1200);
	scr_KSW_AddFish("Variegated Lardfish",spr_KSW_Fish_VariegatedLardfish,spr_KSW_Fish_VariegatedLardfish_Pal_Normal,mage,1,KSW_Phases.none,7400);
	scr_KSW_AddFish("Obsidifish",spr_KSW_Fish_Obsidifish,spr_KSW_Fish_Obsidifish_Pal_Normal,flux,2,KSW_Phases.none,2900);
	scr_KSW_AddFish("Princess Fish",spr_KSW_Fish_PrincessFish,spr_KSW_Fish_PrincessFish_Pal_Normal,flux,2,KSW_Phases.none,3300);
	scr_KSW_AddFish("Flarefin Koi",spr_KSW_Fish_FlarefinKoi,spr_KSW_Fish_FlarefinKoi_Pal_Normal,glimmer,2,KSW_Phases.none,4000);
	scr_KSW_AddFish("Prismite",spr_KSW_Fish_Prismite,spr_KSW_Fish_Prismite_Pal_Normal,flux,2,KSW_Phases.none,4400);
	scr_KSW_AddFish("Golden Carp",spr_KSW_Fish_GoldenCarp,spr_KSW_Fish_GoldenCarp_Pal_Normal,borange,2,KSW_Phases.none,5000);
	scr_KSW_AddFish("Chaos Fish",spr_KSW_Fish_ChaosFish,spr_KSW_Fish_ChaosFish_Pal_Normal,flux,2,KSW_Phases.none,4200);
	scr_KSW_AddFish("Amanita Fungifin",spr_KSW_Fish_AmanitaFungifin,spr_KSW_Fish_AmanitaFungifin_Pal_Normal,mage,3,KSW_Phases.none,6900);
	scr_KSW_AddFish("Angelfish",spr_KSW_Fish_Angelfish,spr_KSW_Fish_Angelfish_Pal_Normal,borange,3,KSW_Phases.none,3600);
	scr_KSW_AddFish("Batfish",spr_KSW_Fish_Batfish,spr_KSW_Fish_Batfish_Pal_Normal,legion,3,KSW_Phases.none,1800);
	scr_KSW_AddFish("Bloody Manowar",spr_KSW_Fish_BloodyManowar,spr_KSW_Fish_BloodyManowar_Pal_Normal,candy,3,KSW_Phases.none,3900);
	scr_KSW_AddFish("Bonefish",spr_KSW_Fish_Bonefish,spr_KSW_Fish_Bonefish_Pal_Normal,mint,3,KSW_Phases.none,3200);
	scr_KSW_AddFish("Bumblebee Tuna",spr_KSW_Fish_BumblebeeTuna,spr_KSW_Fish_BumblebeeTuna_Pal_Normal,borange,3,KSW_Phases.none,2900);
	scr_KSW_AddFish("Bunnyfish",spr_KSW_Fish_Bunnyfish,spr_KSW_Fish_Bunnyfish_Pal_Normal,glimmer,3,KSW_Phases.none,1000);
	scr_KSW_AddFish("Cap'n Tunabeard",spr_KSW_Fish_CapnTunabeard,spr_KSW_Fish_CapnTunabeard_Pal_Normal,candy,3,KSW_Phases.none,2800);
	scr_KSW_AddFish("Catfish",spr_KSW_Fish_Catfish,spr_KSW_Fish_Catfish_Pal_Normal,glimmer,3,KSW_Phases.none,3200);
	scr_KSW_AddFish("Cloudfish",spr_KSW_Fish_Cloudfish,spr_KSW_Fish_Cloudfish_Pal_Normal,glimmer,3,KSW_Phases.none,1400);
	scr_KSW_AddFish("Clownfish",spr_KSW_Fish_Clownfish,spr_KSW_Fish_Clownfish_Pal_Normal,borange,3,KSW_Phases.none,1500);
	scr_KSW_AddFish("Cursedfish",spr_KSW_Fish_Cursedfish,spr_KSW_Fish_Cursedfish_Pal_Normal,mint,3,KSW_Phases.none,1700);
	scr_KSW_AddFish("Demonic Hellfish",spr_KSW_Fish_DemonicHellfish,spr_KSW_Fish_DemonicHellfish_Pal_Normal,candy,3,KSW_Phases.none,1900);
	scr_KSW_AddFish("Derpfish",spr_KSW_Fish_Derpfish,spr_KSW_Fish_Derpfish_Pal_Normal,legion,3,KSW_Phases.none,1600);
	scr_KSW_AddFish("Dirtfish",spr_KSW_Fish_Dirtfish,spr_KSW_Fish_Dirtfish_Pal_Normal,mage,3,KSW_Phases.none,2000);
	scr_KSW_AddFish("Dynamite Fish",spr_KSW_Fish_DynamiteFish,spr_KSW_Fish_DynamiteFish_Pal_Normal,candy,3,KSW_Phases.none,3000);
	scr_KSW_AddFish("Eater of Plankton",spr_KSW_Fish_EaterOfPlankton,spr_KSW_Fish_EaterOfPlankton_Pal_Normal,mage,3,KSW_Phases.none,4000);
	scr_KSW_AddFish("Fallen Starfish",spr_KSW_Fish_FallenStarfish,spr_KSW_Fish_FallenStarfish_Pal_Normal,borange,3,KSW_Phases.none,4400);
	scr_KSW_AddFish("Fishotron",spr_KSW_Fish_Fishotron,spr_KSW_Fish_Fishotron_Pal_Normal,mint,3,KSW_Phases.none,5000);
	scr_KSW_AddFish("Fishron",spr_KSW_Fish_Fishron,spr_KSW_Fish_Fishron_Pal_Normal,glimmer,3,KSW_Phases.none,2000);
	scr_KSW_AddFish("Guide Voodoo Fish",spr_KSW_Fish_GuideVoodooFish,spr_KSW_Fish_GuideVoodooFish_Pal_Normal,candy,3,KSW_Phases.none,2400);
	scr_KSW_AddFish("Harpyfish",spr_KSW_Fish_Harpyfish,spr_KSW_Fish_Harpyfish_Pal_Normal,legion,3,KSW_Phases.none,5200);
	scr_KSW_AddFish("Hungerfish",spr_KSW_Fish_Hungerfish,spr_KSW_Fish_Hungerfish_Pal_Normal,candy,3,KSW_Phases.none,5700);
	scr_KSW_AddFish("Ichorfish",spr_KSW_Fish_Ichorfish,spr_KSW_Fish_Ichorfish_Pal_Normal,borange,3,KSW_Phases.none,4800);
	scr_KSW_AddFish("Scabbardfish",spr_KSW_Fish_InfectedScabbardfish,spr_KSW_Fish_InfectedScabbardfish_Pal_Normal,flux,3,KSW_Phases.none,6300);
	scr_KSW_AddFish("Jewelfish",spr_KSW_Fish_Jewelfish,spr_KSW_Fish_Jewelfish_Pal_Normal,mage,3,KSW_Phases.none,5500);
	scr_KSW_AddFish("Mirage Fish",spr_KSW_Fish_MirageFish,spr_KSW_Fish_MirageFish_Pal_Normal,flux,3,KSW_Phases.none,5900);
	scr_KSW_AddFish("Mudfish",spr_KSW_Fish_Mudfish,spr_KSW_Fish_Mudfish_Pal_Normal,mage,3,KSW_Phases.none,4600);
	scr_KSW_AddFish("Mutant Flinxfin",spr_KSW_Fish_MutantFlinxfin,spr_KSW_Fish_MutantFlinxfin_Pal_Normal,glimmer,3,KSW_Phases.none,6200);
	scr_KSW_AddFish("Pengfish",spr_KSW_Fish_Pengfish,spr_KSW_Fish_Pengfish_Pal_Normal,mage,3,KSW_Phases.none,4300);
	scr_KSW_AddFish("Pixiefish",spr_KSW_Fish_Pixiefish,spr_KSW_Fish_Pixiefish_Pal_Normal,borange,3,KSW_Phases.none,4400);
	scr_KSW_AddFish("Scarab Fish",spr_KSW_Fish_ScarabFish,spr_KSW_Fish_ScarabFish_Pal_Normal,flux,3,KSW_Phases.none,6800);
	scr_KSW_AddFish("Scorpio Fish",spr_KSW_Fish_ScorpioFish,spr_KSW_Fish_ScorpioFish_Pal_Normal,borange,3,KSW_Phases.none,6400);
	scr_KSW_AddFish("Slimefish",spr_KSW_Fish_Slimefish,spr_KSW_Fish_Slimefish_Pal_Normal,mint,3,KSW_Phases.none,5000);
	scr_KSW_AddFish("Spiderfish",spr_KSW_Fish_Spiderfish,spr_KSW_Fish_Spiderfish_Pal_Normal,mage,3,KSW_Phases.none,4700);
	scr_KSW_AddFish("The Fish of Cthulhu",spr_KSW_Fish_TheFishOfCthulhu,spr_KSW_Fish_TheFishOfCthulhu_Pal_Normal,candy,3,KSW_Phases.none,7200);
	scr_KSW_AddFish("Tropical Barracuda",spr_KSW_Fish_TropicalBarracuda,spr_KSW_Fish_TropicalBarracuda_Pal_Normal,legion,3,KSW_Phases.none,6500);
	scr_KSW_AddFish("Tundra Trout",spr_KSW_Fish_TundraTrout,spr_KSW_Fish_TundraTrout_Pal_Normal,mage,3,KSW_Phases.none,4200);
	scr_KSW_AddFish("Unicorn Fish",spr_KSW_Fish_UnicornFish,spr_KSW_Fish_UnicornFish_Pal_Normal,glimmer,3,KSW_Phases.none,4600);
	scr_KSW_AddFish("Wyverntail",spr_KSW_Fish_Wyverntail,spr_KSW_Fish_Wyverntail_Pal_Normal,glimmer,3,KSW_Phases.none,7000);
	scr_KSW_AddFish("Zombie Fish",spr_KSW_Fish_ZombieFish,spr_KSW_Fish_ZombieFish_Pal_Normal,mint,3,KSW_Phases.none,5600);
	scr_KSW_AddFish("Cheri Berry",spr_KSW_Fish_CheriBerry,spr_KSW_Fish_CheriBerry_Pal_Normal,candy,0,KSW_Phases.none,40);
	scr_KSW_AddFish("Chesto Berry",spr_KSW_Fish_ChestoBerry,spr_KSW_Fish_ChestoBerry_Pal_Normal,flux,0,KSW_Phases.none,40);
	scr_KSW_AddFish("Pecha Berry",spr_KSW_Fish_PechaBerry,spr_KSW_Fish_PechaBerry_Pal_Normal,glimmer,0,KSW_Phases.none,40);
	scr_KSW_AddFish("Rawst Berry",spr_KSW_Fish_RawstBerry,spr_KSW_Fish_RawstBerry_Pal_Normal,mage,0,KSW_Phases.none,50);
	scr_KSW_AddFish("Aspear Berry",spr_KSW_Fish_AspearBerry,spr_KSW_Fish_AspearBerry_Pal_Normal,glimmer,0,KSW_Phases.none,40);
	scr_KSW_AddFish("Leppa Berry",spr_KSW_Fish_LeppaBerry,spr_KSW_Fish_LeppaBerry_Pal_Normal,borange,0,KSW_Phases.none,60);
	scr_KSW_AddFish("Oran Berry",spr_KSW_Fish_OranBerry,spr_KSW_Fish_OranBerry_Pal_Normal,legion,0,KSW_Phases.none,50);
	scr_KSW_AddFish("Persim Berry",spr_KSW_Fish_PersimBerry,spr_KSW_Fish_PersimBerry_Pal_Normal,borange,0,KSW_Phases.none,40);
	scr_KSW_AddFish("Lum Berry",spr_KSW_Fish_LumBerry,spr_KSW_Fish_LumBerry_Pal_Normal,mint,0,KSW_Phases.none,50);
	scr_KSW_AddFish("Sitrus Berry",spr_KSW_Fish_SitrusBerry,spr_KSW_Fish_SitrusBerry_Pal_Normal,borange,0,KSW_Phases.none,40);
	scr_KSW_AddFish("Figy Berry",spr_KSW_Fish_FigyBerry,spr_KSW_Fish_FigyBerry_Pal_Normal,borange,0,KSW_Phases.none,40);
	scr_KSW_AddFish("Wiki Berry",spr_KSW_Fish_WikiBerry,spr_KSW_Fish_WikiBerry_Pal_Normal,flux,0,KSW_Phases.none,60);
	scr_KSW_AddFish("Mago Berry",spr_KSW_Fish_MagoBerry,spr_KSW_Fish_MagoBerry_Pal_Normal,glimmer,0,KSW_Phases.none,40);
	scr_KSW_AddFish("Aguav Berry",spr_KSW_Fish_AguavBerry,spr_KSW_Fish_AguavBerry_Pal_Normal,mint,0,KSW_Phases.none,40);
	scr_KSW_AddFish("Iapapa Berry",spr_KSW_Fish_IapapaBerry,spr_KSW_Fish_IapapaBerry_Pal_Normal,borange,0,KSW_Phases.none,50);
	scr_KSW_AddFish("Razz Berry",spr_KSW_Fish_RazzBerry,spr_KSW_Fish_RazzBerry_Pal_Normal,borange,0,KSW_Phases.none,50);
	scr_KSW_AddFish("Bluk Berry",spr_KSW_Fish_BlukBerry,spr_KSW_Fish_BlukBerry_Pal_Normal,flux,0,KSW_Phases.none,50);
	scr_KSW_AddFish("Nanab Berry",spr_KSW_Fish_NanabBerry,spr_KSW_Fish_NanabBerry_Pal_Normal,glimmer,0,KSW_Phases.none,60);
	scr_KSW_AddFish("Wepear Berry",spr_KSW_Fish_WepearBerry,spr_KSW_Fish_WepearBerry_Pal_Normal,mint,0,KSW_Phases.none,50);
	scr_KSW_AddFish("Pinap Berry",spr_KSW_Fish_PinapBerry,spr_KSW_Fish_PinapBerry_Pal_Normal,borange,0,KSW_Phases.none,50);
	scr_KSW_AddFish("Pomeg Berry",spr_KSW_Fish_PomegBerry,spr_KSW_Fish_PomegBerry_Pal_Normal,borange,0,KSW_Phases.none,40);
	scr_KSW_AddFish("Kelpsy Berry",spr_KSW_Fish_KelpsyBerry,spr_KSW_Fish_KelpsyBerry_Pal_Normal,mage,0,KSW_Phases.none,40);
	scr_KSW_AddFish("Qualot Berry",spr_KSW_Fish_QualotBerry,spr_KSW_Fish_QualotBerry_Pal_Normal,borange,0,KSW_Phases.none,40);
	scr_KSW_AddFish("Hondew Berry",spr_KSW_Fish_HondewBerry,spr_KSW_Fish_HondewBerry_Pal_Normal,mint,0,KSW_Phases.none,50);
	scr_KSW_AddFish("Grepa Berry",spr_KSW_Fish_GrepaBerry,spr_KSW_Fish_GrepaBerry_Pal_Normal,borange,0,KSW_Phases.none,60);
	scr_KSW_AddFish("Tamato Berry",spr_KSW_Fish_TamatoBerry,spr_KSW_Fish_TamatoBerry_Pal_Normal,borange,0,KSW_Phases.none,60);
	scr_KSW_AddFish("Cornn Berry",spr_KSW_Fish_CornnBerry,spr_KSW_Fish_CornnBerry_Pal_Normal,flux,0,KSW_Phases.none,60);
	scr_KSW_AddFish("Magost Berry",spr_KSW_Fish_MagostBerry,spr_KSW_Fish_MagostBerry_Pal_Normal,glimmer,0,KSW_Phases.none,50);
	scr_KSW_AddFish("Rabuta Berry",spr_KSW_Fish_RabutaBerry,spr_KSW_Fish_RabutaBerry_Pal_Normal,mint,0,KSW_Phases.none,40);
	scr_KSW_AddFish("Nomel Berry",spr_KSW_Fish_NomelBerry,spr_KSW_Fish_NomelBerry_Pal_Normal,borange,0,KSW_Phases.none,50);
	scr_KSW_AddFish("Spelon Berry",spr_KSW_Fish_SpelonBerry,spr_KSW_Fish_SpelonBerry_Pal_Normal,glimmer,0,KSW_Phases.none,60);
	scr_KSW_AddFish("Pamtre Berry",spr_KSW_Fish_PamtreBerry,spr_KSW_Fish_PamtreBerry_Pal_Normal,flux,0,KSW_Phases.none,50);
	scr_KSW_AddFish("Watmel Berry",spr_KSW_Fish_WatmelBerry,spr_KSW_Fish_WatmelBerry_Pal_Normal,mint,0,KSW_Phases.none,50);
	scr_KSW_AddFish("Durin Berry",spr_KSW_Fish_DurinBerry,spr_KSW_Fish_DurinBerry_Pal_Normal,mint,0,KSW_Phases.none,50);
	scr_KSW_AddFish("Belue Berry",spr_KSW_Fish_BelueBerry,spr_KSW_Fish_BelueBerry_Pal_Normal,flux,0,KSW_Phases.none,50);
	scr_KSW_AddFish("Occa Berry",spr_KSW_Fish_OccaBerry,spr_KSW_Fish_OccaBerry_Pal_Normal,borange,0,KSW_Phases.none,60);
	scr_KSW_AddFish("Passho Berry",spr_KSW_Fish_PasshoBerry,spr_KSW_Fish_PasshoBerry_Pal_Normal,mage,0,KSW_Phases.none,60);
	scr_KSW_AddFish("Wacan Berry",spr_KSW_Fish_WacanBerry,spr_KSW_Fish_WacanBerry_Pal_Normal,mint,0,KSW_Phases.none,40);
	scr_KSW_AddFish("Rindo Berry",spr_KSW_Fish_RindoBerry,spr_KSW_Fish_RindoBerry_Pal_Normal,mint,0,KSW_Phases.none,40);
	scr_KSW_AddFish("Yache Berry",spr_KSW_Fish_YacheBerry,spr_KSW_Fish_YacheBerry_Pal_Normal,legion,0,KSW_Phases.none,40);
	scr_KSW_AddFish("Chople Berry",spr_KSW_Fish_ChopleBerry,spr_KSW_Fish_ChopleBerry_Pal_Normal,candy,0,KSW_Phases.none,40);
	scr_KSW_AddFish("Kebia Berry",spr_KSW_Fish_KebiaBerry,spr_KSW_Fish_KebiaBerry_Pal_Normal,mint,0,KSW_Phases.none,50);
	scr_KSW_AddFish("Shuca Berry",spr_KSW_Fish_ShucaBerry,spr_KSW_Fish_ShucaBerry_Pal_Normal,borange,0,KSW_Phases.none,50);
	scr_KSW_AddFish("Coba Berry",spr_KSW_Fish_CobaBerry,spr_KSW_Fish_CobaBerry_Pal_Normal,legion,0,KSW_Phases.none,50);
	scr_KSW_AddFish("Payapa Berry",spr_KSW_Fish_PayapaBerry,spr_KSW_Fish_PayapaBerry_Pal_Normal,flux,0,KSW_Phases.none,60);
	scr_KSW_AddFish("Tanga Berry",spr_KSW_Fish_TangaBerry,spr_KSW_Fish_TangaBerry_Pal_Normal,borange,0,KSW_Phases.none,50);
	scr_KSW_AddFish("Charti Berry",spr_KSW_Fish_ChartiBerry,spr_KSW_Fish_ChartiBerry_Pal_Normal,borange,0,KSW_Phases.none,50);
	scr_KSW_AddFish("Kasib Berry",spr_KSW_Fish_KasibBerry,spr_KSW_Fish_KasibBerry_Pal_Normal,flux,0,KSW_Phases.none,50);
	scr_KSW_AddFish("Haban Berry",spr_KSW_Fish_HabanBerry,spr_KSW_Fish_HabanBerry_Pal_Normal,candy,0,KSW_Phases.none,60);
	scr_KSW_AddFish("Colbur Berry",spr_KSW_Fish_ColburBerry,spr_KSW_Fish_ColburBerry_Pal_Normal,flux,0,KSW_Phases.none,60);
	scr_KSW_AddFish("Babiri Berry",spr_KSW_Fish_BabiriBerry,spr_KSW_Fish_BabiriBerry_Pal_Normal,mint,0,KSW_Phases.none,60);
	scr_KSW_AddFish("Chilan Berry",spr_KSW_Fish_ChilanBerry,spr_KSW_Fish_ChilanBerry_Pal_Normal,borange,0,KSW_Phases.none,60);
	scr_KSW_AddFish("Liechi Berry",spr_KSW_Fish_LiechiBerry,spr_KSW_Fish_LiechiBerry_Pal_Normal,borange,0,KSW_Phases.none,40);
	scr_KSW_AddFish("Ganlon Berry",spr_KSW_Fish_GanlonBerry,spr_KSW_Fish_GanlonBerry_Pal_Normal,flux,0,KSW_Phases.none,40);
	scr_KSW_AddFish("Salac Berry",spr_KSW_Fish_SalacBerry,spr_KSW_Fish_SalacBerry_Pal_Normal,mint,0,KSW_Phases.none,40);
	scr_KSW_AddFish("Petaya Berry",spr_KSW_Fish_PetayaBerry,spr_KSW_Fish_PetayaBerry_Pal_Normal,borange,0,KSW_Phases.none,40);
	scr_KSW_AddFish("Apicot Berry",spr_KSW_Fish_ApicotBerry,spr_KSW_Fish_ApicotBerry_Pal_Normal,legion,0,KSW_Phases.none,40);
	scr_KSW_AddFish("Lansat Berry",spr_KSW_Fish_LansatBerry,spr_KSW_Fish_LansatBerry_Pal_Normal,glimmer,0,KSW_Phases.none,50);
	scr_KSW_AddFish("Starf Berry",spr_KSW_Fish_StarfBerry,spr_KSW_Fish_StarfBerry_Pal_Normal,mint,0,KSW_Phases.none,50);
	scr_KSW_AddFish("Enigma Berry",spr_KSW_Fish_EnigmaBerry,spr_KSW_Fish_EnigmaBerry_Pal_Normal,mage,0,KSW_Phases.none,50);
	scr_KSW_AddFish("Micle Berry",spr_KSW_Fish_MicleBerry,spr_KSW_Fish_MicleBerry_Pal_Normal,mint,0,KSW_Phases.none,50);
	scr_KSW_AddFish("Custap Berry",spr_KSW_Fish_CustapBerry,spr_KSW_Fish_CustapBerry_Pal_Normal,candy,0,KSW_Phases.none,60);
	scr_KSW_AddFish("Jaboca Berry",spr_KSW_Fish_JabocaBerry,spr_KSW_Fish_JabocaBerry_Pal_Normal,borange,0,KSW_Phases.none,60);
	scr_KSW_AddFish("Rowap Berry",spr_KSW_Fish_RowapBerry,spr_KSW_Fish_RowapBerry_Pal_Normal,legion,0,KSW_Phases.none,40);
	scr_KSW_AddFish("Roseli Berry",spr_KSW_Fish_RoseliBerry,spr_KSW_Fish_RoseliBerry_Pal_Normal,candy,0,KSW_Phases.none,60);
	scr_KSW_AddFish("Kee Berry",spr_KSW_Fish_KeeBerry,spr_KSW_Fish_KeeBerry_Pal_Normal,glimmer,0,KSW_Phases.none,50);
	scr_KSW_AddFish("Maranga Berry",spr_KSW_Fish_MarangaBerry,spr_KSW_Fish_MarangaBerry_Pal_Normal,borange,0,KSW_Phases.none,40);
	scr_KSW_AddFish("Chainsaw Fish",spr_KSW_Fish_ChainsawFish,spr_KSW_Fish_ChainsawFish_Pal_Normal,mage,1,KSW_Phases.night,6000,-16,0);
	scr_KSW_AddFish("7 Colored Fish",spr_KSW_Fish_7ColoredFish,spr_KSW_Fish_7ColoredFish_Pal_Normal,mint,2,KSW_Phases.night,9000,-10,-12);
	scr_KSW_AddFish("Magikarp",spr_KSW_Fish_Magikarp,spr_KSW_Fish_Magikarp_Pal_Normal,candy,0,KSW_Phases.day,500,-4,0);
	scr_KSW_AddFish("Gyrados",spr_KSW_Fish_Gyrados,spr_KSW_Fish_Gyrados_Pal_Normal,legion,2,KSW_Phases.day,20000,-22,4);
	scr_KSW_AddFish("Goldeen",spr_KSW_Fish_Goldeen,spr_KSW_Fish_Goldeen_Pal_Normal,borange,0,KSW_Phases.day,400,-1,0);
	scr_KSW_AddFish("Seaking",spr_KSW_Fish_Seaking,spr_KSW_Fish_Seaking_Pal_Normal,borange,1,KSW_Phases.day,4000,-2,0);
	scr_KSW_AddFish("Horsea",spr_KSW_Fish_Horsea,spr_KSW_Fish_Horsea_Pal_Normal,mage,0,KSW_Phases.afternoon,350,1,0);
	scr_KSW_AddFish("Seadra",spr_KSW_Fish_Seadra,spr_KSW_Fish_Seadra_Pal_Normal,mage,1,KSW_Phases.afternoon,2500,2,-1);
	scr_KSW_AddFish("Kingdra",spr_KSW_Fish_Kingdra,spr_KSW_Fish_Kingdra_Pal_Normal,mage,2,KSW_Phases.afternoon,12000,-2,2);
	scr_KSW_AddFish("Krabby",spr_KSW_Fish_Krabby,spr_KSW_Fish_Krabby_Pal_Normal,candy,0,KSW_Phases.day,1000,0,-2);
	scr_KSW_AddFish("Kingler",spr_KSW_Fish_Kingler,spr_KSW_Fish_Kingler_Pal_Normal,candy,1,KSW_Phases.day,7000,0,-4);
	scr_KSW_AddFish("Omanyte",spr_KSW_Fish_Omanyte,spr_KSW_Fish_Omanyte_Pal_Normal,legion,1,KSW_Phases.afternoon,4000);
	scr_KSW_AddFish("Omastar",spr_KSW_Fish_Omastar,spr_KSW_Fish_Omastar_Pal_Normal,legion,2,KSW_Phases.afternoon,9000,0,-2);
	scr_KSW_AddFish("Lapras",spr_KSW_Fish_Lapras,spr_KSW_Fish_Lapras_Pal_Normal,mage,2,KSW_Phases.day,30000,-6,6);
	scr_KSW_AddFish("Kabuto",spr_KSW_Fish_Kabuto,spr_KSW_Fish_Kabuto_Pal_Normal,borange,1,KSW_Phases.night,3000);
	scr_KSW_AddFish("Kabutops",spr_KSW_Fish_Kabutops,spr_KSW_Fish_Kabutops_Pal_Normal,borange,2,KSW_Phases.night,8000,0,-2);
	scr_KSW_AddFish("Tentacool",spr_KSW_Fish_Tentacool,spr_KSW_Fish_Tentacool_Pal_Normal,mage,0,KSW_Phases.night,1000,-1,0);
	scr_KSW_AddFish("Tentacruel",spr_KSW_Fish_Tentacruel,spr_KSW_Fish_Tentacruel_Pal_Normal,mage,1,KSW_Phases.night,4200);
	scr_KSW_AddFish("Staryu",spr_KSW_Fish_Staryu,spr_KSW_Fish_Staryu_Pal_Normal,borange,0,KSW_Phases.afternoon,750);
	scr_KSW_AddFish("Starmie",spr_KSW_Fish_Starmie,spr_KSW_Fish_Starmie_Pal_Normal,flux,1,KSW_Phases.afternoon,3200);
	scr_KSW_AddFish("Slowpoke",spr_KSW_Fish_Slowpoke,spr_KSW_Fish_Slowpoke_Pal_Normal,glimmer,0,KSW_Phases.day,800);
	scr_KSW_AddFish("Slowbro",spr_KSW_Fish_Slowbro,spr_KSW_Fish_Slowbro_Pal_Normal,glimmer,1,KSW_Phases.day,3600,-2,-2);
	scr_KSW_AddFish("Slowking",spr_KSW_Fish_Slowking,spr_KSW_Fish_Slowking_Pal_Normal,glimmer,2,KSW_Phases.day,9800,0,-3);
	scr_KSW_AddFish("Shellder",spr_KSW_Fish_Shellder,spr_KSW_Fish_Shellder_Pal_Normal,flux,0,KSW_Phases.day,600,-1,0);
	scr_KSW_AddFish("Cloyster",spr_KSW_Fish_Cloyster,spr_KSW_Fish_Cloyster_Pal_Normal,flux,1,KSW_Phases.day,2700,-2,-2);
	scr_KSW_AddFish("Squirtle",spr_KSW_Fish_Squirtle,spr_KSW_Fish_Squirtle_Pal_Normal,legion,1,KSW_Phases.day,1200);
	scr_KSW_AddFish("Wartortle",spr_KSW_Fish_Wartortle,spr_KSW_Fish_Wartortle_Pal_Normal,legion,2,KSW_Phases.day,9000);
	scr_KSW_AddFish("Blastoise",spr_KSW_Fish_Blastoise,spr_KSW_Fish_Blastoise_Pal_Normal,legion,3,KSW_Phases.day,20000);
	scr_KSW_AddFish("Seel",spr_KSW_Fish_Seel,spr_KSW_Fish_Seel_Pal_Normal,glimmer,0,KSW_Phases.afternoon,900);
	scr_KSW_AddFish("Dewgong",spr_KSW_Fish_Dewgong,spr_KSW_Fish_Dewgong_Pal_Normal,glimmer,1,KSW_Phases.afternoon,2600,-5,-1);
	scr_KSW_AddFish("Psyduck",spr_KSW_Fish_Psyduck,spr_KSW_Fish_Psyduck_Pal_Normal,borange,0,KSW_Phases.day,750,0,-2);
	scr_KSW_AddFish("Golduck",spr_KSW_Fish_Golduck,spr_KSW_Fish_Golduck_Pal_Normal,mage,1,KSW_Phases.day,3000,2,4);
	scr_KSW_AddFish("Poliwag",spr_KSW_Fish_Poliwag,spr_KSW_Fish_Poliwag_Pal_Normal,legion,0,KSW_Phases.afternoon,500,-2,0);
	scr_KSW_AddFish("Poliwhirl",spr_KSW_Fish_Poliwhirl,spr_KSW_Fish_Poliwhirl_Pal_Normal,legion,1,KSW_Phases.day,2200);
	scr_KSW_AddFish("Poliwrath",spr_KSW_Fish_Poliwrath,spr_KSW_Fish_Poliwrath_Pal_Normal,legion,2,KSW_Phases.day,8000,0,-4);
	scr_KSW_AddFish("Politoed",spr_KSW_Fish_Politoed,spr_KSW_Fish_Politoed_Pal_Normal,mint,2,KSW_Phases.day,7200,0,-2);
	scr_KSW_AddFish("Dratini",spr_KSW_Fish_Dratini,spr_KSW_Fish_Dratini_Pal_Normal,mage,1,KSW_Phases.afternoon,1000,-2,-1);
	scr_KSW_AddFish("Dragonair",spr_KSW_Fish_Dragonair,spr_KSW_Fish_Dragonair_Pal_Normal,mage,2,KSW_Phases.afternoon,6900,-5,0);
	scr_KSW_AddFish("Dragonite",spr_KSW_Fish_Dragonite,spr_KSW_Fish_Dragonite_Pal_Normal,borange,3,KSW_Phases.afternoon,22000,0,4);
	scr_KSW_AddFish("Godzilla",spr_KSW_Fish_Godzilla,spr_KSW_Fish_Godzilla_Pal_Normal,mint,3,KSW_Phases.day,100000,-10,14);
	scr_KSW_AddFish("Rahab",spr_KSW_Fish_Rahab,spr_KSW_Fish_Rahab_Pal_Normal,glimmer,2,KSW_Phases.night,8000);
	scr_KSW_AddFish("Plesioth",spr_KSW_Fish_Plesioth,spr_KSW_Fish_Plesioth_Pal_Normal,glimmer,3,KSW_Phases.afternoon,80000,-16,18);
	scr_KSW_AddFish("Cacodemon",spr_KSW_Fish_Cacodemon,spr_KSW_Fish_Cacodemon_Pal_Normal,mint,3,KSW_Phases.night,6600,-6,4);
	scr_KSW_AddFish("Wolpole",spr_KSW_Fish_Wolpole,spr_KSW_Fish_Wolpole_Pal_Normal,glimmer,0,KSW_Phases.night,400,4,1);
	scr_KSW_AddFish("Water Dumple",spr_KSW_Fish_WaterDumple,spr_KSW_Fish_WaterDumple_Pal_Normal,glimmer,1,KSW_Phases.night,1200,-6,-1);
	scr_KSW_AddFish("Yellow Wollyhop",spr_KSW_Fish_YellowWollyhop,spr_KSW_Fish_YellowWollyhop_Pal_Normal,glimmer,1,KSW_Phases.afternoon,2700,-2,3);
	scr_KSW_AddFish("Toady Bloyster",spr_KSW_Fish_ToadyBloyster,spr_KSW_Fish_ToadyBloyster_Pal_Normal,glimmer,2,KSW_Phases.day,6600,-17,0);
	scr_KSW_AddFish("Puckering Blinnow",spr_KSW_Fish_PuckeringBlinnow,spr_KSW_Fish_PuckeringBlinnow_Pal_Normal,glimmer,0,KSW_Phases.day,5400,-11,-1);
	scr_KSW_AddFish("Fish Taco",spr_KSW_Fish_FishTaco,spr_KSW_Fish_FishTaco_Pal_Normal,borange,3,KSW_Phases.none,2500,0,0);
	scr_KSW_AddFish("Swedish Fish",spr_KSW_Fish_SwedishFish,spr_KSW_Fish_SwedishFish_Pal_Normal,mint,3,KSW_Phases.day,10,-30,0);
	scr_KSW_AddFish("Archfiend Skull",spr_KSW_Fish_ArchfiendSkull,spr_KSW_Fish_ArchfiendSkull_Pal_Normal,mint,3,KSW_Phases.night,5000);
	scr_KSW_AddFish("Ghost Hamster",spr_KSW_Fish_GhostHamster,spr_KSW_Fish_GhostHamster_Pal_Normal,mint,3,KSW_Phases.night,7800);
	scr_KSW_AddFish("Mizzle",spr_KSW_Fish_Mizzle,spr_KSW_Fish_Mizzle_Pal_Normal,mage,1,KSW_Phases.night,2000,-8,8);
	scr_KSW_AddFish("Pluey",spr_KSW_Fish_Pluey,spr_KSW_Fish_Pluey_Pal_Normal,mage,2,KSW_Phases.none,4800);
	scr_KSW_AddFish("Annoying Dogfish",spr_KSW_Fish_AnnoyingDogfish,spr_KSW_Fish_AnnoyingDogfish_Pal_Normal,mint,3,KSW_Phases.day,20015);
	scr_KSW_AddFish("SPAM[FISH]",spr_KSW_Fish_Spamfish,spr_KSW_Fish_Spamfish_Pal_Normal,glimmer,3,KSW_Phases.none,1997,-26,-12);
	scr_KSW_AddFish("Mr Ant Tenna",spr_KSW_Fish_MrAntTenna,spr_KSW_Fish_MrAntTenna_Pal_Normal,tvtime,3,KSW_Phases.none,300000,0,20).isTenna = true;
	scr_KSW_AddFish("Quirky Knight",spr_KSW_Fish_QuirkyKnight,spr_KSW_Fish_QuirkyKnight_Pal_Normal,mint,3,KSW_Phases.night,20000,0,8);
	scr_KSW_AddFish("Big Lenny",spr_KSW_Fish_Big_Lenny_Normal,spr_KSW_Fish_Big_Lenny_Pal_Normal,flux,3,KSW_Phases.night,100000,23,10);
	scr_KSW_AddFish("Game Shark",spr_KSW_Fish_GameShark,spr_KSW_Fish_GameShark_Pal_Normal,legion,3,KSW_Phases.afternoon,8000,-12,4);
	scr_KSW_AddFish("Egg Fish",spr_KSW_Fish_EggFish,spr_KSW_Fish_EggFish_Pal_Normal,borange,1,KSW_Phases.afternoon,2000,-4,0);
	scr_KSW_AddFish("Ikachan",spr_KSW_Fish_Ikachan,spr_KSW_Fish_Ikachan_Pal_Normal,mage,2,KSW_Phases.night,4600);
	scr_KSW_AddFish("Ironhead",spr_KSW_Fish_Ironhead,spr_KSW_Fish_Ironhead_Pal_Normal,legion,3,KSW_Phases.night,55480,-46,-10);
	scr_KSW_AddFish("Sea-Shroom",spr_KSW_Fish_SeaShroom,spr_KSW_Fish_SeaShroom_Pal_Normal,mint,2,KSW_Phases.night,5000);
	scr_KSW_AddFish("Tangle Kelp",spr_KSW_Fish_TangleKelp,spr_KSW_Fish_TangleKelp_Pal_Normal,mint,2,KSW_Phases.day,5000);
	scr_KSW_AddFish("Snorkel Zombie",spr_KSW_Fish_SnorkelZombie,spr_KSW_Fish_SnorkelZombie_Pal_Normal,mint,3,KSW_Phases.night,12000,-16,6);
	scr_KSW_AddFish("Rotten Flesh",spr_KSW_Fish_RottenFlesh,spr_KSW_Fish_RottenFlesh_Pal_Normal,borange,0,KSW_Phases.none,40);
	scr_KSW_AddFish("Leather Boots",spr_KSW_Fish_LeatherBoots,spr_KSW_Fish_LeatherBoots_Pal_Normal,borange,0,KSW_Phases.none,60);
	scr_KSW_AddFish("Leather",spr_KSW_Fish_Leather,spr_KSW_Fish_Leather_Pal_Normal,borange,0,KSW_Phases.none,50);
	scr_KSW_AddFish("Bowl",spr_KSW_Fish_Bowl,spr_KSW_Fish_Bowl_Pal_Normal,borange,0,KSW_Phases.none,60);
	scr_KSW_AddFish("Stick",spr_KSW_Fish_Stick,spr_KSW_Fish_Stick_Pal_Normal,borange,0,KSW_Phases.none,40);
	scr_KSW_AddFish("Bone",spr_KSW_Fish_Bone,spr_KSW_Fish_Bone_Pal_Normal,legion,0,KSW_Phases.none,50);
	scr_KSW_AddFish("String",spr_KSW_Fish_String,spr_KSW_Fish_String_Pal_Normal,mage,0,KSW_Phases.none,40);
	scr_KSW_AddFish("Baggie",spr_KSW_Fish_Baggie,spr_KSW_Fish_Baggie_Pal_Normal,borange,3,KSW_Phases.none,20000,0,3);
	scr_KSW_AddFish("Omni Fish",spr_KSW_Fish_OmniFish,spr_KSW_Fish_OmniFish_Pal_Normal,legion,3,KSW_Phases.night,500000);
	scr_KSW_AddFish("Invader Squid",spr_KSW_Fish_InvaderSquid,spr_KSW_Fish_InvaderSquid_Pal_Normal,mint,1,KSW_Phases.night,3000);
	scr_KSW_AddFish("Invader Crab",spr_KSW_Fish_InvaderCrab,spr_KSW_Fish_InvaderCrab_Pal_Normal,mage,1,KSW_Phases.night,2000);
	scr_KSW_AddFish("Invader Octopus",spr_KSW_Fish_InvaderOctopus,spr_KSW_Fish_InvaderOctopus_Pal_Normal,borange,1,KSW_Phases.night,1000);
	scr_KSW_AddFish("Invader UFO",spr_KSW_Fish_InvaderUFO,spr_KSW_Fish_InvaderUFO_Pal_Normal,flux,3,KSW_Phases.night,12800);
	scr_KSW_AddFish("Kalamar",spr_KSW_Fish_Kalamar,spr_KSW_Fish_Kalamar_Pal_Normal,legion,2,KSW_Phases.night,4000);
	scr_KSW_AddFish("Pipe Fiend",spr_KSW_Fish_PipeFiend,spr_KSW_Fish_PipeFiend_Pal_Normal,legion,2,KSW_Phases.night,5000);
	scr_KSW_AddFish("Prey",spr_KSW_Fish_Prey,spr_KSW_Fish_Prey_Pal_Normal,legion,2,KSW_Phases.night,4500);
	scr_KSW_AddFish("Lil' Blub",spr_KSW_Fish_LilBlub,spr_KSW_Fish_LilBlub_Pal_Normal,mint,3,KSW_Phases.night,15000,0,10);
	scr_KSW_AddFish("Strawberry",spr_KSW_Fish_Strawberry,spr_KSW_Fish_Strawberry_Pal_Normal,candy,0,KSW_Phases.none,40);
	scr_KSW_AddFish("Tomato",spr_KSW_Fish_Tomato,spr_KSW_Fish_Tomato_Pal_Normal,candy,0,KSW_Phases.none,60);
	scr_KSW_AddFish("Cherries",spr_KSW_Fish_Cherries,spr_KSW_Fish_Cherries_Pal_Normal,mint,0,KSW_Phases.none,40);
	scr_KSW_AddFish("Watermelon",spr_KSW_Fish_Watermelon,spr_KSW_Fish_Watermelon_Pal_Normal,candy,0,KSW_Phases.none,60);
	scr_KSW_AddFish("Melon",spr_KSW_Fish_Melon,spr_KSW_Fish_Melon_Pal_Normal,mint,0,KSW_Phases.none,60);
	scr_KSW_AddFish("Orange",spr_KSW_Fish_Orange,spr_KSW_Fish_Orange_Pal_Normal,borange,0,KSW_Phases.none,50);
	scr_KSW_AddFish("Bananas",spr_KSW_Fish_Bananas,spr_KSW_Fish_Bananas_Pal_Normal,glimmer,0,KSW_Phases.none,50);
	scr_KSW_AddFish("Peach",spr_KSW_Fish_Peach,spr_KSW_Fish_Peach_Pal_Normal,glimmer,0,KSW_Phases.none,50);
	scr_KSW_AddFish("Carrot",spr_KSW_Fish_Carrot,spr_KSW_Fish_Carrot_Pal_Normal,borange,0,KSW_Phases.none,50);
	scr_KSW_AddFish("Green Pepper",spr_KSW_Fish_GreenPepper,spr_KSW_Fish_GreenPepper_Pal_Normal,mint,0,KSW_Phases.none,40);
	scr_KSW_AddFish("Kabocha",spr_KSW_Fish_Kabocha,spr_KSW_Fish_Kabocha_Pal_Normal,mint,0,KSW_Phases.none,60);
	scr_KSW_AddFish("Peas",spr_KSW_Fish_Peas,spr_KSW_Fish_Peas_Pal_Normal,mint,0,KSW_Phases.none,40);
	scr_KSW_AddFish("Corn",spr_KSW_Fish_Corn,spr_KSW_Fish_Corn_Pal_Normal,borange,0,KSW_Phases.none,60);
	scr_KSW_AddFish("Milk Carton",spr_KSW_Fish_MilkCarton,spr_KSW_Fish_MilkCarton_Pal_Normal,mage,0,KSW_Phases.none,60);
	scr_KSW_AddFish("Milk Bottle",spr_KSW_Fish_MilkBottle,spr_KSW_Fish_MilkBottle_Pal_Normal,mage,0,KSW_Phases.none,50);
	scr_KSW_AddFish("Bread",spr_KSW_Fish_Bread,spr_KSW_Fish_Bread_Pal_Normal,legion,0,KSW_Phases.none,40);
	scr_KSW_AddFish("Donut",spr_KSW_Fish_Donut,spr_KSW_Fish_Donut_Pal_Normal,legion,0,KSW_Phases.none,40);
	scr_KSW_AddFish("Pancakes",spr_KSW_Fish_Pancakes,spr_KSW_Fish_Pancakes_Pal_Normal,candy,0,KSW_Phases.none,50);
	scr_KSW_AddFish("Sandwich",spr_KSW_Fish_Sandwich,spr_KSW_Fish_Sandwich_Pal_Normal,mint,0,KSW_Phases.none,50);
	scr_KSW_AddFish("Hot Dog",spr_KSW_Fish_HotDog,spr_KSW_Fish_HotDog_Pal_Normal,glimmer,0,KSW_Phases.none,50);
	scr_KSW_AddFish("Burger",spr_KSW_Fish_Burger,spr_KSW_Fish_Burger_Pal_Normal,borange,0,KSW_Phases.none,60);
	scr_KSW_AddFish("Roast Chicken",spr_KSW_Fish_RoastChicken,spr_KSW_Fish_RoastChicken_Pal_Normal,borange,0,KSW_Phases.none,60);
	scr_KSW_AddFish("Lobster Dish",spr_KSW_Fish_LobsterDish,spr_KSW_Fish_LobsterDish_Pal_Normal,candy,0,KSW_Phases.none,60);
	scr_KSW_AddFish("Fried Eggs",spr_KSW_Fish_FriedEggs,spr_KSW_Fish_FriedEggs_Pal_Normal,legion,0,KSW_Phases.none,40);
	scr_KSW_AddFish("French Fries",spr_KSW_Fish_FrenchFries,spr_KSW_Fish_FrenchFries_Pal_Normal,candy,0,KSW_Phases.none,50);
	scr_KSW_AddFish("Cupcake",spr_KSW_Fish_Cupcake,spr_KSW_Fish_Cupcake_Pal_Normal,glimmer,0,KSW_Phases.none,50);
	scr_KSW_AddFish("Cookie",spr_KSW_Fish_Cookie,spr_KSW_Fish_Cookie_Pal_Normal,borange,0,KSW_Phases.none,40);
	scr_KSW_AddFish("Shaved Ice",spr_KSW_Fish_ShavedIce,spr_KSW_Fish_ShavedIce_Pal_Normal,mage,0,KSW_Phases.none,40);
	scr_KSW_AddFish("Ice Cream Cone",spr_KSW_Fish_IceCreamCone,spr_KSW_Fish_IceCreamCone_Pal_Normal,mage,0,KSW_Phases.none,50);
	scr_KSW_AddFish("Ice Cream Bar",spr_KSW_Fish_IceCreamBar,spr_KSW_Fish_IceCreamBar_Pal_Normal,legion,0,KSW_Phases.none,50);
	scr_KSW_AddFish("Flan",spr_KSW_Fish_Flan,spr_KSW_Fish_Flan_Pal_Normal,borange,0,KSW_Phases.none,60);
	scr_KSW_AddFish("Cream Soda",spr_KSW_Fish_CreamSoda,spr_KSW_Fish_CreamSoda_Pal_Normal,mint,0,KSW_Phases.none,50);
	scr_KSW_AddFish("Orange Juice",spr_KSW_Fish_OrangeJuice,spr_KSW_Fish_OrangeJuice_Pal_Normal,borange,0,KSW_Phases.none,50);
	scr_KSW_AddFish("Coffee",spr_KSW_Fish_Coffee,spr_KSW_Fish_Coffee_Pal_Normal,legion,0,KSW_Phases.none,40);
	scr_KSW_AddFish("Soda Can",spr_KSW_Fish_SodaCan,spr_KSW_Fish_SodaCan_Pal_Normal,candy,0,KSW_Phases.none,40);
	scr_KSW_AddFish("Candy Cane",spr_KSW_Fish_CandyCane,spr_KSW_Fish_CandyCane_Pal_Normal,candy,0,KSW_Phases.none,40);
	scr_KSW_AddFish("Candy",spr_KSW_Fish_Candy,spr_KSW_Fish_Candy_Pal_Normal,candy,0,KSW_Phases.none,40);
	scr_KSW_AddFish("Crepe",spr_KSW_Fish_Crepe,spr_KSW_Fish_Crepe_Pal_Normal,glimmer,0,KSW_Phases.none,50);
	scr_KSW_AddFish("Maxim Tomato",spr_KSW_Fish_MaximTomato,spr_KSW_Fish_MaximTomato_Pal_Normal,candy,1,KSW_Phases.none,2000);
	scr_KSW_AddFish("Invincibility Candy",spr_KSW_Fish_InvincibilityCandy,spr_KSW_Fish_InvincibilityCandy_Pal_Normal,glimmer,1,KSW_Phases.none,2000);
	scr_KSW_AddFish("Extra Life",spr_KSW_Fish_ExtraLife,spr_KSW_Fish_ExtraLife_Pal_Normal,glimmer,2,KSW_Phases.none,2500);
	scr_KSW_AddFish("Treasure Chest",spr_KSW_Fish_TreasureChest,spr_KSW_Fish_TreasureChest_Pal_Normal,candy,3,KSW_Phases.none,15000,-2);
	scr_KSW_AddFish("Star Coin",spr_KSW_Fish_StarCoin,spr_KSW_Fish_StarCoin_Pal_Normal,borange,3,KSW_Phases.none,10000);
	scr_KSW_AddFish("Gold Medal",spr_KSW_Fish_GoldMedal,spr_KSW_Fish_GoldMedal_Pal_Normal,glimmer,2,KSW_Phases.none,1000);
	scr_KSW_AddFish("Gold Coin",spr_KSW_Fish_GoldCoin,spr_KSW_Fish_GoldCoin_Pal_Normal,glimmer,2,KSW_Phases.none,100);
	scr_KSW_AddFish("Whip",spr_KSW_Fish_Whip,spr_KSW_Fish_Whip_Pal_Normal,borange,2,KSW_Phases.none,6800);
	scr_KSW_AddFish("Crystal Ball",spr_KSW_Fish_CrystalBall,spr_KSW_Fish_CrystalBall_Pal_Normal,mage,2,KSW_Phases.none,2000);
	scr_KSW_AddFish("Lucky Cat",spr_KSW_Fish_LuckyCat,spr_KSW_Fish_LuckyCat_Pal_Normal,glimmer,2,KSW_Phases.none,500);
	scr_KSW_AddFish("Seiryu Sword",spr_KSW_Fish_SeiryuSword,spr_KSW_Fish_SeiryuSword_Pal_Normal,mage,2,KSW_Phases.none,1420);
	scr_KSW_AddFish("Screw Attack",spr_KSW_Fish_ScrewAttack,spr_KSW_Fish_ScrewAttack_Pal_Normal,borange,2,KSW_Phases.none,8000);
	scr_KSW_AddFish("Echigo Candy",spr_KSW_Fish_EchigoCandy,spr_KSW_Fish_EchigoCandy_Pal_Normal,borange,2,KSW_Phases.none,8000);
	scr_KSW_AddFish("Phanto Mask",spr_KSW_Fish_PhantoMask,spr_KSW_Fish_PhantoMask_Pal_Normal,legion,2,KSW_Phases.none,2780);
	scr_KSW_AddFish("Star Stone",spr_KSW_Fish_StarStone,spr_KSW_Fish_StarStone_Pal_Normal,borange,2,KSW_Phases.none,8210);
	scr_KSW_AddFish("Beast Fang",spr_KSW_Fish_BeastFang,spr_KSW_Fish_BeastFang_Pal_Normal,borange,2,KSW_Phases.none,7300);
	scr_KSW_AddFish("Bandanna",spr_KSW_Fish_Bandanna,spr_KSW_Fish_Bandanna_Pal_Normal,candy,2,KSW_Phases.none,1990);
	scr_KSW_AddFish("Springtime",spr_KSW_Fish_Springtime,spr_KSW_Fish_Springtime_Pal_Normal,candy,2,KSW_Phases.none,2500);
	scr_KSW_AddFish("Seasons Heart",spr_KSW_Fish_SeasonsHeart,spr_KSW_Fish_SeasonsHeart_Pal_Normal,glimmer,2,KSW_Phases.none,2500);
	scr_KSW_AddFish("Dime",spr_KSW_Fish_Dime,spr_KSW_Fish_Dime_Pal_Normal,borange,2,KSW_Phases.none,10);
	scr_KSW_AddFish("Glass Slipper",spr_KSW_Fish_GlassSlipper,spr_KSW_Fish_GlassSlipper_Pal_Normal,mage,2,KSW_Phases.none,1200);
	scr_KSW_AddFish("Goblet",spr_KSW_Fish_Goblet,spr_KSW_Fish_Goblet_Pal_Normal,borange,2,KSW_Phases.none,800);
	scr_KSW_AddFish("Sauce Pan",spr_KSW_Fish_SaucePan,spr_KSW_Fish_SaucePan_Pal_Normal,legion,2,KSW_Phases.none,10);
	scr_KSW_AddFish("Brass Knuckle",spr_KSW_Fish_BrassKnuckle,spr_KSW_Fish_BrassKnuckle_Pal_Normal,legion,2,KSW_Phases.none,2000);
	scr_KSW_AddFish("Amber Rose",spr_KSW_Fish_AmberRose,spr_KSW_Fish_AmberRose_Pal_Normal,glimmer,2,KSW_Phases.none,2210);
	scr_KSW_AddFish("Fish Fossil",spr_KSW_Fish_FishFossil,spr_KSW_Fish_FishFossil_Pal_Normal,legion,2,KSW_Phases.none,8250);
	scr_KSW_AddFish("Beast Fossil",spr_KSW_Fish_BeastFossil,spr_KSW_Fish_BeastFossil_Pal_Normal,legion,2,KSW_Phases.none,2422);
	scr_KSW_AddFish("Nunchucks",spr_KSW_Fish_Nunchucks,spr_KSW_Fish_Nunchucks_Pal_Normal,legion,2,KSW_Phases.none,5548);
	scr_KSW_AddFish("Machine Parts",spr_KSW_Fish_MachineParts,spr_KSW_Fish_MachineParts_Pal_Normal,mint,2,KSW_Phases.none,1213);
	scr_KSW_AddFish("Bucket",spr_KSW_Fish_Bucket,spr_KSW_Fish_Bucket_Pal_Normal,borange,2,KSW_Phases.none,200);
	scr_KSW_AddFish("Summertime",spr_KSW_Fish_Summertime,spr_KSW_Fish_Summertime_Pal_Normal,mint,2,KSW_Phases.none,2500);
	scr_KSW_AddFish("Power Paintbrush",spr_KSW_Fish_PowerPaintbrush,spr_KSW_Fish_PowerPaintbrush_Pal_Normal,mage,2,KSW_Phases.none,2220);
	scr_KSW_AddFish("100-Dollar Coin",spr_KSW_Fish_100DollarCoin,spr_KSW_Fish_100DollarCoin_Pal_Normal,glimmer,2,KSW_Phases.none,1000);
	scr_KSW_AddFish("Ancient Gem",spr_KSW_Fish_AncientGem,spr_KSW_Fish_AncientGem_Pal_Normal,candy,2,KSW_Phases.none,6800);
	scr_KSW_AddFish("Falcon Helmet",spr_KSW_Fish_FalconHelmet,spr_KSW_Fish_FalconHelmet_Pal_Normal,candy,2,KSW_Phases.none,4100);
	scr_KSW_AddFish("Dud",spr_KSW_Fish_Dud,spr_KSW_Fish_Dud_Pal_Normal,borange,2,KSW_Phases.none,30);
	scr_KSW_AddFish("Cell Phone",spr_KSW_Fish_CellPhone,spr_KSW_Fish_CellPhone_Pal_Normal,candy,2,KSW_Phases.none,4021);
	scr_KSW_AddFish("Truth Mirror",spr_KSW_Fish_TruthMirror,spr_KSW_Fish_TruthMirror_Pal_Normal,glimmer,2,KSW_Phases.none,5000);
	scr_KSW_AddFish("Star Tiara",spr_KSW_Fish_StarTiara,spr_KSW_Fish_StarTiara_Pal_Normal,glimmer,2,KSW_Phases.none,4082);
	scr_KSW_AddFish("Koopa Shell",spr_KSW_Fish_KoopaShell,spr_KSW_Fish_KoopaShell_Pal_Normal,mint,2,KSW_Phases.none,800);
	scr_KSW_AddFish("Falchion",spr_KSW_Fish_Falchion,spr_KSW_Fish_Falchion_Pal_Normal,mint,2,KSW_Phases.none,3250);
	scr_KSW_AddFish("Warrior Shield",spr_KSW_Fish_WarriorShield,spr_KSW_Fish_WarriorShield_Pal_Normal,glimmer,2,KSW_Phases.none,5000);
	scr_KSW_AddFish("Unicorn Horn",spr_KSW_Fish_UnicornHorn,spr_KSW_Fish_UnicornHorn_Pal_Normal,mage,2,KSW_Phases.none,8030);
	scr_KSW_AddFish("Autumntime",spr_KSW_Fish_Autumntime,spr_KSW_Fish_Autumntime_Pal_Normal,borange,2,KSW_Phases.none,2500);
	scr_KSW_AddFish("Three-Star Cane",spr_KSW_Fish_ThreeStarCane,spr_KSW_Fish_ThreeStarCane_Pal_Normal,glimmer,2,KSW_Phases.none,2220);
	scr_KSW_AddFish("Broken Bowl",spr_KSW_Fish_BrokenBowl,spr_KSW_Fish_BrokenBowl_Pal_Normal,mage,2,KSW_Phases.none,50);
	scr_KSW_AddFish("Tut Mask",spr_KSW_Fish_TutMask,spr_KSW_Fish_TutMask_Pal_Normal,glimmer,2,KSW_Phases.none,1600);
	scr_KSW_AddFish("Mr Saturn",spr_KSW_Fish_MrSaturn,spr_KSW_Fish_MrSaturn_Pal_Normal,candy,2,KSW_Phases.none,1200);
	scr_KSW_AddFish("Armor",spr_KSW_Fish_Armor,spr_KSW_Fish_Armor_Pal_Normal,legion,2,KSW_Phases.none,2120);
	scr_KSW_AddFish("Treasure Box",spr_KSW_Fish_TreasureBox,spr_KSW_Fish_TreasureBox_Pal_Normal,borange,2,KSW_Phases.none,1000);
	scr_KSW_AddFish("Mannequin",spr_KSW_Fish_Mannequin,spr_KSW_Fish_Mannequin_Pal_Normal,legion,2,KSW_Phases.none,3000);
	scr_KSW_AddFish("Gold Crown",spr_KSW_Fish_GoldCrown,spr_KSW_Fish_GoldCrown_Pal_Normal,glimmer,2,KSW_Phases.none,5280);
	scr_KSW_AddFish("King Cape",spr_KSW_Fish_KingCape,spr_KSW_Fish_KingCape_Pal_Normal,candy,2,KSW_Phases.none,5080);
	scr_KSW_AddFish("Model Ship",spr_KSW_Fish_ModelShip,spr_KSW_Fish_ModelShip_Pal_Normal,borange,2,KSW_Phases.none,8000);
	scr_KSW_AddFish("Sun Ring",spr_KSW_Fish_SunRing,spr_KSW_Fish_SunRing_Pal_Normal,borange,2,KSW_Phases.none,8000);
	scr_KSW_AddFish("Wintertime",spr_KSW_Fish_Wintertime,spr_KSW_Fish_Wintertime_Pal_Normal,legion,2,KSW_Phases.none,2500);
	scr_KSW_AddFish("Gold Watering Can",spr_KSW_Fish_GoldWateringCan,spr_KSW_Fish_GoldWateringCan_Pal_Normal,flux,2,KSW_Phases.none,2000);
	scr_KSW_AddFish("Katana",spr_KSW_Fish_Katana,spr_KSW_Fish_Katana_Pal_Normal,legion,2,KSW_Phases.none,9900);
	scr_KSW_AddFish("Charm",spr_KSW_Fish_Charm,spr_KSW_Fish_Charm_Pal_Normal,legion,2,KSW_Phases.none,8000);
	scr_KSW_AddFish("Xmas Tree",spr_KSW_Fish_XmasTree,spr_KSW_Fish_XmasTree_Pal_Normal,mint,2,KSW_Phases.none,4000);
	scr_KSW_AddFish("Kong Barrel",spr_KSW_Fish_KongBarrel,spr_KSW_Fish_KongBarrel_Pal_Normal,borange,2,KSW_Phases.none,1500);
	scr_KSW_AddFish("Ramia Scale",spr_KSW_Fish_RamiaScale,spr_KSW_Fish_RamiaScale_Pal_Normal,mint,2,KSW_Phases.none,1280);
	scr_KSW_AddFish("Shiny Bamboo",spr_KSW_Fish_ShinyBamboo,spr_KSW_Fish_ShinyBamboo_Pal_Normal,mint,2,KSW_Phases.none,6000);
	scr_KSW_AddFish("Tire",spr_KSW_Fish_Tire,spr_KSW_Fish_Tire_Pal_Normal,legion,2,KSW_Phases.none,1100);
	scr_KSW_AddFish("Spirit Charm",spr_KSW_Fish_SpiritCharm,spr_KSW_Fish_SpiritCharm_Pal_Normal,mage,2,KSW_Phases.none,7850);
	scr_KSW_AddFish("Pegasus Wing",spr_KSW_Fish_PegasusWing,spr_KSW_Fish_PegasusWing_Pal_Normal,mage,2,KSW_Phases.none,4280);
	scr_KSW_AddFish("Raccoon Doll",spr_KSW_Fish_RaccoonDoll,spr_KSW_Fish_RaccoonDoll_Pal_Normal,borange,2,KSW_Phases.none,8150);
	scr_KSW_AddFish("Shell Whistle",spr_KSW_Fish_ShellWhistle,spr_KSW_Fish_ShellWhistle_Pal_Normal,mage,2,KSW_Phases.none,8200);
	scr_KSW_AddFish("Orichalcum",spr_KSW_Fish_Orichalcum,spr_KSW_Fish_Orichalcum_Pal_Normal,legion,2,KSW_Phases.none,5120);
	scr_KSW_AddFish("Platinum Ring",spr_KSW_Fish_PlatinumRing,spr_KSW_Fish_PlatinumRing_Pal_Normal,legion,2,KSW_Phases.none,4000);
	scr_KSW_AddFish("Triforce",spr_KSW_Fish_Triforce,spr_KSW_Fish_Triforce_Pal_Normal,glimmer,2,KSW_Phases.none,8000);
	scr_KSW_AddFish("Crewmate",spr_KSW_Fish_Crewmate,spr_KSW_Fish_Crewmate_Pal_Normal,candy,2,KSW_Phases.none,6666);
	scr_KSW_AddFish("Super Mushroom",spr_KSW_Fish_SuperMushroom,spr_KSW_Fish_SuperMushroom_Pal_Normal,candy,2,KSW_Phases.none,2000);
	scr_KSW_AddFish("Soda",spr_KSW_Fish_Soda,spr_KSW_Fish_Soda_Pal_Normal,legion,2,KSW_Phases.none,18000);
	scr_KSW_AddFish("Grape Soda",spr_KSW_Fish_GrapeSoda,spr_KSW_Fish_GrapeSoda_Pal_Normal,flux,2,KSW_Phases.none,1800);
	scr_KSW_AddFish("Kirburger",spr_KSW_Fish_Kirburger,spr_KSW_Fish_Kirburger_Pal_Normal,borange,2,KSW_Phases.none,5000);
	#endregion
}